import java.lang.System.getenv

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
  // Apply the foojay-resolver plugin to allow automatic download of JDKs
  id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "glassthought-sandbox"
include("app")

val THORG_ROOT = getenv("THORG_ROOT")

/*
 * This allows the project to depend on locally built versions of these libraries.
 */
includeBuild("${THORG_ROOT}/source/libraries/kotlin-mp") {
  dependencySubstitution {
    substitute(module("com.asgard:asgardCore")).using(project(":asgardCore"))
    substitute(module("com.asgard:asgardGit")).using(project(":asgardGit"))
    substitute(module("com.asgard:asgardTestTools")).using(project(":asgardTestTools"))
    substitute(module("com.thorg:thorgCoreTestTools")).using(project(":thorgCoreTestTools"))
    substitute(module("com.thorg:thorgCore")).using(project(":thorgCore"))
  }
}
