/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.7.10"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0")
}

val MAIN_CLASS = "gt.sandbox.AppKt"
application {
    // Define the main class for the application.
    mainClass.set(MAIN_CLASS)
}

//tasks.register<JavaExec>("runMainQuietly") {
//    group = "application"
//    description = "Runs the main class quietly"
//    mainClass.set(MAIN_CLASS)
//    classpath = sourceSets["main"].runtimeClasspath
//
//    doFirst {
//        // Set the logging level to quiet before running the task
//        logging.captureStandardOutput(LogLevel.QUIET)
//        logging.captureStandardError(LogLevel.QUIET)
//    }
//}
tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
