/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gt.kotlin.sandbox

import kotlinx.coroutines.*

fun main() = runBlocking<Unit> {

    val mainMillisStamp = System.currentTimeMillis()

    val promise1 = async {
        ThreadUtils.printWithThreadInfo("print within 1st async {}")
        delay(1000L) // simulate some long-running computation
        ThreadUtils.printWithThreadInfo("print after sleep 1st async {}")
        "1st async result"
    }

    val promise2 = async {
        ThreadUtils.printWithThreadInfo("print after sleep 2nd async {}")
        delay(1000L)
        ThreadUtils.printWithThreadInfo("print after sleep 2nd async {}")
        // e some long-running computation
        "2nd async result"
    }
    println(promise1.await())
    println(promise2.await())

    println("Elapsed time: ${System.currentTimeMillis() - mainMillisStamp} ms")
}
