/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gt.kotlin.sandbox

import kotlinx.coroutines.*
import java.util.stream.IntStream


suspend fun performLongRequest(msg: String): String {
    return withContext(Dispatchers.IO) {

        ThreadUtils.sleep(500)
        ThreadUtils.printWithThreadInfo("Within subroutine input: $msg")

        String.format("MessageResultAfterBlockingOperation for [%s]", msg)
    }
}

fun main() {

    ThreadUtils.printWithThreadInfo("Example using async with more requests than cores on a laptop")

    val mainMillisStamp = System.currentTimeMillis();


    runBlocking {

        val deferredObjects = IntStream.range(0, 8).mapToObj { i ->
            val deferred = async { performLongRequest("${i}-request") }
            deferred
        }

        for(deferred in deferredObjects) {
            ThreadUtils.printWithThreadInfo("Deferred result: " + deferred.await())
        }

        ThreadUtils.printWithThreadInfo(
            "Total time taken: " +
                    (System.currentTimeMillis() - mainMillisStamp) + "ms"
        )
    }
}
